import "./globals.css";
import { Roboto } from "next/font/google";
import Link from "next/link";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          roboto.className +
          " h-full bg-zinc-900 flex-col items-center justify-center container m-auto"
        }
      >
        <div className="flex justify-start items-center">
          <ul className=" flex gap-3 justify-center flex-row">
            <li>
              <Link
                href={"/"}
                className=" text-white text-lg hover:text-slate-200"
              >
                Form
              </Link>
            </li>
            <li>
              <Link
                href={"/stats"}
                className=" text-white text-lg hover:text-slate-200"
              >
                Stats
              </Link>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
